---
# yamllint disable rule:line-length
#
# Repo: https://github.com/Paul-Houser/StartTree
# Pagina de inicio..: ~/.cache/StartTree/index.html
# Ruta Firefox: file:///home/USUARIO/.cache/StartTree/index.html
#
# Tras un cambio, hay que ejecutar: starttree.py
font_size: 20
theme: intrigue
tree_1:
  Nuke Code:
    e-hentai: https://e-hentai.org/tag/language:spanish
    hitomi.la: https://hitomi.la/index-spanish.html
    latinohentai: https://latinohentai.com/genre/audio-latino/
    nhentai: https://nhentai.net/
  Texto:
    figlet-ascii: https://www.askapache.com/online-tools/figlet-ascii/
    generadordenombres: https://generadordenombres.online/instagram/
    wordunscrambler: https://www.wordunscrambler.net
    fontgenerator: https://www.fontgenerator.org/popular
    twitter-fonts: https://glyphy.io/font-generator/twitter-fonts
    dino-ipsum: https://dinoipsum.com/
    bacon-ipsum: https://baconipsum.com/json-api/
    SYMBL: https://symbl.cc/es/
    ðŸ”¥MagLit (shortener): https://maglit.me/
tree_2:
  Unicode:
    emoji-charts: https://www.unicode.org/emoji/charts/full-emoji-list.html
    emoji-table: https://unicode-table.com/es/emoji/
    rozen-maiden-ascii: https://4-ch.net/ascii/kareha.pl/1143036729
    punycode: https://www.punycoder.com/
  Otros Utiles:
    aprende-vim 1: https://victorhck.gitbook.io/aprende-vim/
    aprende-vim 2: https://vimaroo.vercel.app/
    artbreeder: https://www.artbreeder.com/create/mixer
    example-hashes: https://hashcat.net/wiki/doku.php?id=example_hashes
    iconfinder: https://www.iconfinder.com/
    imgcreator: https://imgcreator.zmo.ai/ai-generator
    Magnet-Links-Editor: https://madeby.lynx.st/magnets/
    mathmap: https://mathmap.quantamagazine.org/
    neovim plugins: https://dotfyle.com/
    shortcuts for soundcloud: https://usethekeyboard.com/soundcloud/
    sunpath3d: https://drajmarsh.bitbucket.io/sunpath3d.html
    the-true-size-of: https://www.thetruesize.com/
    vim-tips: https://www.cs.swarthmore.edu/oldhelp/vim/home.html
    vimcolorschemes: https://vimcolorschemes.com/i/trending
tree_3:
  Tech:
    aime: https://www.aime.info/blog/deep-learning-gpu-benchmarks-2022/
    bottleneck-calculator: https://pc-builds.com/es/bottleneck-calculator/
    braille-ascii: https://lachlanarthur.github.io/Braille-ASCII-Art/
    commandlinefu: https://www.commandlinefu.com/
    cron-descriptor: https://bradymholt.github.io/cron-expression-descriptor/
    cron-parser: https://elmah.io/tools/cron-parser/
    cyberchef: https://gchq.github.io/CyberChef/
    github-download-directory: "https://download-directory.github.io/"
    github-folder-downloader: "https://gitfolderdownloader.github.io/"
    github-repo-downloader: "https://repo-downloader.pages.dev/"
    gpu-database: https://www.techpowerup.com/gpu-specs/
    image-to-braille: https://505e06b2.github.io/Image-to-Braille/
    iso-debian: https://www.debian.org/CD/http-ftp/
    keyboard/mouse test: https://skill-test.net/
    latitude.to: https://latitude.to/
    postimages: https://postimages.org/
    psucalculator: https://outervision.com/power-supply-calculator
    quiteaplaylist: https://quiteaplaylist.com/
    revistas ðŸ”–: "https://freemagazines.top/computers-hardwares-softwares"
    speedometer: https://browserbench.org/Speedometer2.0/
    suite-tools: https://browserleaks.com/ip
    translate-images: https://translate.yandex.com/es/ocr
    unicode-converter: https://www.branah.com/unicode-converter
    utf-8 encoder/decoder: https://mothereff.in/utf-8
    wicar: https://www.wicar.org/test-malware.html
    youtube-metadata: https://mattw.io/youtube-metadata/
  IA:
    ai-photo-enhancer: https://app.remini.ai/
    aime-blog: https://www.aime.info/blog/en/
    civitai: https://civitai.com/
    craiyon: https://www.craiyon.com/
    deepl-translator: https://www.deepl.com/translator
    deepnude: https://app.deepnude.cc/upload
    dezgo: https://dezgo.com/
    lalal.ai: https://www.lalal.ai/
    moises.ai: https://moises.ai/es/features/vocal-remover/
    pfpmaker: https://pfpmaker.com/
    prompthero: https://prompthero.com/waifu-diffusion-prompts
    stability.ai: https://stability.ai/
    stable-diffusion: https://huggingface.co/spaces/stabilityai/stable-diffusion
    vocalremover: https://vocalremover.org/
    waifu2x: http://waifu2x.udp.jp/
tree_4:
  StableDiffusion:
    Anime AI Prompts: https://aituts.com/anime-artists-ai-prompts/
    Character bones: https://toyxyz.gumroad.com/l/ciojz
    ComfyUI: https://comfyanonymous.github.io/ComfyUI_examples/controlnet/
    controlnet: https://github.com/lllyasviel/ControlNet
    dreambooth: https://stable-diffusion-art.com/dreambooth/
    GPU Buyer's Guide: https://rentry.org/stablediffgpubuy#hentai-for-cheapskates
    install Anything V3: https://aituts.com/anything-anime-stable-diffusion/
    Local Installation: https://www.reddit.com/r/stablediffusion/wiki/local/
    install Dreambooth: https://medium.com/mlearning-ai/how-to-run-dreambooth-locally-a-step-by-step-gyu-88c028ab01a4
    Models Cookbook: https://rentry.org/hdgrecipes#hdg-stable-diffusion-models-cookbook
    Multi-ControlNet: https://twitter.com/toyxyz3/status/1629620938894643200
    NovelAI Prompt Guide: https://aituts.com/novelai-anime-prompt-techniques/
    pix2pix-zero: https://pix2pixzero.github.io/
    Pose-helper: https://civitai.com/models/11573/zpose-fighting-styles-1-pose-helper
    Posemaker: https://avatarposemaker.deezein.com/
    Ultimate RunPod Tutorial: https://youtu.be/QN1vdGhjcRc
    Posable-riggify: https://3dcinetv.gumroad.com/l/osezw
tree_5:
  Album:
    hikarinoakari: https://hikarinoakari.com/
    okamimiost: https://okamimiost.com/
    sukidesuost: https://sukidesuost.info/
    classical-music: https://classical-music-download.com/
    j-pop: https://jpop.xyz/
    realovemusic: https://www.patreon.com/realovemusic
    mixxx-controllers: https://manual.mixxx.org/2.3/en/hardware/manuals.html#controllers
    micro-audiotest: https://www.audiotestkitchen.com/
    djtechtools: https://djtechtools.com/
    Guide To Studio Scratches: https://studioscratches.com/guide-to-studio-scratches/
    Scratch Techniques: https://schoolofscratch.com/
    Audio Test Tones: https://www.audiocheck.net/testtones_index.php
  Ocio:
    al_gamewith: https://gamewith.jp/azurlane/
    al_pasokau: https://pasokau.com/category/allcharacter
    al_augment-guide: https://tinyurl.com/3yz7zm8z
    favorgk: https://www.favorgk.com/search?q=Marin+Kitagawa&options%5Bprefix%5D=last
  Fansub:
    hakoniwa: https://hakoniwasubs.wordpress.com/
    fukou-da: https://fukou-da.net/
    beatz-anime: https://www.beatz-anime.com/
tree_6:
  Bitcoin:
    coinalyze: https://coinalyze.net/futures-data/global-charts/uniswap/
    cryptorank: https://cryptorank.io/price/uniswap/exchanges
    defillama: https://defillama.com/languages
    halving_countdown: https://www.bitcoinblockhalf.com/?ref=cryptophercolumbus
    mvrv: https://www.lookintobitcoin.com/charts/mvrv-zscore/
    pi_cycle: https://www.lookintobitcoin.com/charts/pi-cycle-top-indicator/
    pi_multiple: https://bitcoinition.com/charts/pimultiple/
    pump_map: https://cignals.io/pumpmap
    whalestats: https://www.whalestats.com/analysis-of-the-top-100-eth-wallets/holding
tree_7:
  ColorWheel:
    color-wheel: https://www.canva.com/colors/color-wheel/
  Picker:
    color-picker: https://a.atmos.washington.edu/~ovens/javascript/colorpicker.html
    colorhexa: https://www.colorhexa.com/
  Generator:
    Color palette generator (IA): https://huemint.com/
  Tools:
    aa-generator: https://www.learnui.design/tools/accessible-color-generator.html
    color-contrast-1: https://colourcontrast.cc/
    color-contrast-2: https://colorshark.io/
    color-picker-comparison: https://bottosson.github.io/misc/colorpicker/#F8F8FF
    color-scales: https://components.ai/color-scale/5PAxBy4dabxhohtd2w1B
    colourco.de: https://www.toptal.com/designers/colourcode/monochrome-color-builder
    coolors: https://coolors.co/
    gradient-generator-1: https://learnui.design/tools/gradient-generator.html
    gradient-generator-2: https://colordesigner.io/gradient-generator
    hcolor: https://hcolor.info/en/
    hlc-wizard: https://hclwizard.org/
    hotpot.ai: https://hotpot.ai/color-generator
    hue.tools: https://hue.tools/?format=hex
    la-flor: https://htmlcolors.com/shades-and-tints
    random-colors: https://www.crispedge.com/random-colors
    randoma11y: https://randoma11y.com/
    shadegenerator: https://www.shadegenerator.com/BD1366-FADAD7
    shadowlord: https://noeldelgado.github.io/shadowlord/
    shapefactory-duotome: https://duotone.shapefactory.co/?f=26b7a0&t=3d3f4c
    shapefactory-pigment: https://pigment.shapefactory.co/?d=0&a=E1D05C&b=F4F1CA
    tint-tone-shade: https://gradients.app/en/shades/
    tints-shades: https://noeldelgado.github.io/shadowlord/#000000
    visualize_colors: https://artistpigments.org/visualize_colors
    web-color-tool: https://color.joelb.dev/
    webgradients: https://webgradients.com/
  ColorNames:
    colorxs: https://www.colorxs.com/
    encycolorpedia: https://encycolorpedia.com/
    colorpedia: https://veli.ee/colorpedia/?c=F8F8FF
    colorswall: https://colorswall.com/es
